package star_wars;

public class MainPrincipal {

	public static void main(String[] args) {
		// TODO Auto-generated method stub
			IJedi Anakin= new ();
			System.out.println("Personaje numero 1 : ");
			System.out.println();
			Anakin.setAlias("Ani, Darth Vader, Lord Vader");
			Anakin.setNombre("Anakin Skywalker");
			Anakin.setRaza("Humano");
			Anakin.setSexo('H');
			Anakin.setEstatura(1.88);
			Anakin.setPeso(84.0);
			Anakin.setColorojos("Azul(Anakin)");
			Anakin.setColorpelo("Castaño");
			Anakin.setOcupacion("Jedi");
			Anakin.setNacionalidad("Tatooine");
			Anakin.setAfiliacion("Imperio galactico");
			Anakin.setTitulo("Caballero Jedi");
			System.out.println(Anakin.toString());
			System.out.println();
			System.out.println("Personaje numero 2 : ");
			System.out.println();
			ISith Anakin2 =new Sith();
			Vader",Anakin.getNombre(),"Cyborg",Anakin.getSexo(),2.02,136.0,"Amarillo","Calvo","
			Sith",Anakin.getNacionalidad(),true, "Escuadron de la Muerte");
			System.out.println(Anakin2.toString());
			System.out.println();
			IJedi Jedi=new Jedi();
			System.out.println();
			System.out.println("Personaje numero 3 : ");
			System.out.println();
			Jedi.setAlias("Yoda");
			Jedi.setNombre("Especie de Yoda");
			Jedi.setRaza("Yoda");
			Jedi.setSexo('H');
			Jedi.setEstatura(0.66);
			Jedi.setPeso(17.0);
			Jedi.setColorojos("Marron");
			Jedi.setColorpelo("Castaño, Blanco");
			Jedi.setOcupacion("Jedi");
			Jedi.setNacionalidad("Coruscant");
			Jedi.setAfiliacion("Republica");
			Jedi.setTitulo("Gran Maestro de la Orden Jedi");
			System.out.println(Jedi.toString());
			System.out.println();
			IJedi Luke= new Jedi();
			System.out.println();
			System.out.println("Personaje numero 4 : ");
			System.out.println();
			Luke.setAlias("Lukito");
			Luke.setNombre("Luke Skywalker");
			Luke.setRaza("Humano");
			Luke.setSexo('H');
			Luke.setEstatura(1.80);
			Luke.setPeso(90.0);
			Luke.setColorojos("Azul");
			Luke.setColorpelo("Castaño");
			Luke.setOcupacion("Jedi");
			Luke.setNacionalidad("Tatooine");
			Luke.setAfiliacion("Republica");
			Luke.setTitulo("Caballero Jedi");
			System.out.println(Luke.toString());
			System.out.println();
			IDroides R2=new Droides();
			System.out.println();
			System.out.println("Personaje numero 5 : ");
			System.out.println();
			R2.setAlias("REDOS");
			R2.setNombre("R2-D2");
			R2.setRaza("Droide");
			R2.setSexo('D');
			R2.setEstatura(0.80);
			R2.setPeso(90.0);
			R2.setColorojos(null);
			R2.setColorpelo(null);
			R2.setOcupacion(null);
			R2.setNacionalidad("Naboo");
			R2.setAfiliacion("Republica");
			R2.setTitulo("Droide astromecanico");
			R2.setAndar(false);
			R2.setHablar(false);
			R2.setNavegar(false);
			R2.setReparar(true);
			R2.setOperar(true);
			System.out.println(R2.toString());
			R2.navegacionEstelar();
			R2.interpretarIdiomas();
			R2.repararNave();
			R2.repararDroide();
			R2.operarHumano(Anakin);
			System.out.println();
			IDroides C3=new Droides();
			System.out.println();
			System.out.println("Personaje 6 : ");
			System.out.println();
			C3.setAlias("C3PO Y 3PO");
			C3.setNombre("C3-PO");
			C3.setRaza("Droide");
			C3.setSexo('D');
			C3.setEstatura(1.80);
			C3.setColorojos(null);
			C3.setColorpelo(null);
			C3.setOcupacion("Droide de protocolo");
			C3.setNacionalidad("Naboo");
			C3.setAfiliacion("Republica");
			C3.setTitulo("Droide astromecanico");
			C3.setAndar(true);
			C3.setHablar(true);
			C3.setNavegar(false);
			C3.setReparar(true);
			C3.setOperar(true);
			System.out.println(C3.toString());
			C3.navegacionEstelar();
			C3.interpretarIdiomas();
			C3.repararNave();
			C3.repararDroide();
			C3.operarHumano(Anakin);
			System.out.println();
			IJedi OBI=new Jedi();
			System.out.println();
			System.out.println("Personaje numero 7 : ");
			System.out.println();
			OBI.setAlias("Ben Kenobi");
			OBI.setNombre("Obi - Wan - Kenobi");
			OBI.setRaza("Humano");
			OBI.setSexo('H');
			OBI.setEstatura(1.82);
			OBI.setPeso(80.0);
			OBI.setColorojos("Azul grisaceo");
			OBI.setColorpelo("Castaño Rojizo");
			OBI.setOcupacion("Jedi");
			OBI.setNacionalidad("Tatooine");
			OBI.setAfiliacion("Republica");
			OBI.setTitulo("Maestro de la Orden Jedi");
			System.out.println(OBI.toString());
			System.out.println();
			IPersonaje HAN= new Personaje();
			System.out.println();
			System.out.println("Personaje numero 8 : ");
			System.out.println();
			HAN.setAlias("HAN");
			HAN.setNombre("HAN SOLO");
			HAN.setRaza("Humano");
			HAN.setSexo('H');
			HAN.setEstatura(1.85);
			HAN.setPeso(90.0);
			HAN.setColorojos("Marron Oscuro");
			HAN.setColorpelo("Negro");
			HAN.setOcupacion("Soldado");
			HAN.setNacionalidad("Corellia");
			System.out.println(HAN.toString());
			System.out.println();
			IPersonaje CHEWBACCA= new Personaje();
			System.out.println();
			System.out.println("Personaje numero 9 : ");
			System.out.println();
			CHEWBACCA.setAlias("CHEWI");
			CHEWBACCA.setNombre("CHEWBACCA");
			CHEWBACCA.setRaza("Wookiee");
			CHEWBACCA.setSexo('H');
			CHEWBACCA.setEstatura(2.25);
			CHEWBACCA.setPeso(130.0);
			CHEWBACCA.setColorojos("Negro");
			CHEWBACCA.setColorpelo("Marron");
			CHEWBACCA.setOcupacion("Soldado");
			CHEWBACCA.setNacionalidad("Kaskyyyk");
			System.out.println(CHEWBACCA.toString());
			System.out.println();
			System.out.print(Anakin.getNombre());
			OBI.Presentarse();
			System.out.print(R2.getNombre());
			R2.Hablar();
			System.out.print(R2.getAlias());
			System.out.print(OBI.getNombre());
			OBI.Luchar();
			System.out.print(HAN.getNombre());
			HAN.Morir();
	
	}

}
